//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nutrition.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Descriptions = new HashSet<Description>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<double> Calories { get; set; }
        public Nullable<double> Carbohydrates { get; set; }
        public Nullable<double> Fats { get; set; }
        public Nullable<double> Proteins { get; set; }
        public Nullable<double> Sugars { get; set; }
        public Nullable<double> Serving { get; set; }
    
        public virtual ICollection<Description> Descriptions { get; set; }
    }
}
